services:
  backend:
    build: ./backend
    container_name: hospital-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: hospital
    depends_on:
      - db
    volumes: 
     # - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:8.0
    container_name: hospital-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hospital
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
